# -----------------------------------------------------------------------------
# REF:  https://pnpm.io/settings
# -----------------------------------------------------------------------------

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - "@jsse/*"
allowBuilds:
  esbuild: true
